### ISSUE TITLE
(2 points) Make product cards

### ISSUE THREAD

**Issue by Its-Alann** [Its-Alann/groupD-soen341project2022#103]

**Comment by Its-Alann** [comment]
Make the design for how the item is displayed

**Comment by Its-Alann** [comment]
@LeonZhang7 do you have the dimensions of the mockup product cards? Like the image size for example?

**Comment by LeonZhang7** [comment]
**Each product card should have the following characteristics**
- Width: 285 px
- Height: 445 px
- Background colour of the card: #F4F5F7

**The image of the product card should have the following dimensions:**
- Width: 285 px
- Height: 300px

**That leaves an area where the name & price of the item can be put onto, this area should have the following dimensions:**
- Width: 285 px
- Height: 145px

**Text information**
- Item name: Abel / size: 24 / #3A3A3A
- Item description: Abel / size: 16 / #969696
- Item price: Abel / size: 20 / #686969
- padding-top: 10px
- padding-left: 10px
