### ISSUE TITLE
(1 point) Create navbar

### ISSUE THREAD

**Issue by Its-Alann** [Its-Alann/groupD-soen341project2022#106]

**Comment by Its-Alann** [comment]
Create a navbar that will be used by all the pages. The design should be based on the mockup below:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/76508163/153644619-267720fc-faf1-4fc3-8f01-83bc07937551.png">

**Comment by harri012** [comment]
Version 1 of Navbar is waiting for review and details of it can be seen on pull request #125.

![image](https://user-images.githubusercontent.com/97982249/154833151-ecc57620-7200-45d5-b3e6-11a067eee897.png)
