### ISSUE TITLE
(1 point) Create footer

### ISSUE THREAD

**Issue by Its-Alann** [Its-Alann/groupD-soen341project2022#107]

**Comment by Its-Alann** [comment]
Create a footer that will be used in all the pages. The design show be based on the mockup below: 

<img width="677" alt="image" src="https://user-images.githubusercontent.com/76508163/153644251-60a91eea-8085-4a2e-997e-e621fadb82fd.png">

**Comment by dange2** [comment]
@LeonZhang7 Hi, do you have the dimensions of the footer?

**Comment by LeonZhang7** [comment]
I saw that you set the height to 11%, it should be fine for the elements we have as of right now

**Comment by Its-Alann** [comment]
@dange2 Just realized that the footer covers the product cards, you think you can make it stick to the bottom of the page?
![image](https://user-images.githubusercontent.com/76508163/154827797-53c56694-11f8-43f9-b4ea-a570c8bf2721.png)

**Comment by dange2** [comment]
@LeonZhang7 I mean for the different sections! Like characteristics and dimensions so that I can input them in the CSS file to make it look like the mockup you had done.
