### ISSUE TITLE
User Story: Sellers

### ISSUE THREAD

**Issue by Its-Alann** [Its-Alann/groupD-soen341project2022#140]
As a seller I want to be able to publish my products on the website because I want the buyers to browse and buy them.

- [x] #141
- [x] #142
- [x] #144
- [x] #145
- [x] #146

Acceptance Tests:
- [x] When product is added to listings, it should show on the website
- [x] When product info is edited, it should change on the website
- [x] Seller log in page differs from regular user page
- [x] A seller should only see his products and should not see other listings from other sellers

**Comment by georgia1515** [comment]
Risk assessments:
<img width="865" alt="Screen Shot 2022-03-20 at 11 44 59 PM" src="https://user-images.githubusercontent.com/77301007/159202697-6d84c113-53a1-43ba-a524-1d501e7721be.png">

**Comment by Its-Alann** [comment]
Story Points Explanations:

![image](https://user-images.githubusercontent.com/76508163/159203154-c2369d15-c5a0-44f3-a22d-5c2bd47b0e3b.png)

![image](https://user-images.githubusercontent.com/76508163/159203172-b3978cfa-c573-4037-ae16-59575187d54c.png)
