### ISSUE TITLE
User story: Managing Your Profile

### ISSUE THREAD

**Issue by harri012** [Its-Alann/groupD-soen341project2022#91]
As a user, I want to be able to manage my profile because I want to update my information accordingly to my needs.

- [x] #97
- [x] #93
- [x] #98
- [x] #94
- [x] #95
- [x] #139

Acceptance Tests:

- [x] If the user clicks on the edit button, it will redirect to the corresponding modification page.
- [x] If the user clicks on the cancel button, his modification is cancelled, the user will be redirected to the main page and the tab is closed
- [x] The user information overrides after modification is accepted.

Story Points Explanation:

![image](https://user-images.githubusercontent.com/78436038/155454277-300b5e2d-ce7f-4f34-9f41-dd8b8db14f37.png)

**Comment by Its-Alann** [comment]
Risk Assesments: 

![image](https://user-images.githubusercontent.com/76508163/155452298-5333702b-b921-477f-9cfd-324b591515e2.png)
